name: bokeh
channels:
- anaconda
- asmeurer
dependencies:
- beautiful-soup=4.3.2=py27_0
- bokeh=0.9.2=np19py27_0
- boto=2.38.0=py27_0
- certifi=14.05.14=py27_0
- colorama=0.3.3=py27_0
- coverage=3.7.1=py27_0
- flask=0.10.1=py27_1
- funcsigs=0.4=py27_0
- gevent=1.0.1=py27_0
- gevent-websocket=0.9.3=py27_0
- greenlet=0.4.7=py27_0
- itsdangerous=0.24=py27_0
- jinja2=2.7.3=py27_1
- libsodium=0.4.5=0
- markupsafe=0.23=py27_0
- mock=1.2.0=py27_0
- ncurses=5.9=1
- nose=1.3.7=py27_0
- numpy=1.9.2=py27_0
- openssl=1.0.1k=1
- pbr=1.3.0=py27_0
- pip=7.1.0=py27_0
- pygments=2.0.2=py27_0
- python=2.7.10=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.4=py27_0
- pyyaml=3.11=py27_1
- pyzmq=14.7.0=py27_0
- readline=6.2.5=1
- requests=2.7.0=py27_0
- setuptools=18.0.1=py27_0
- six=1.9.0=py27_0
- sqlite=3.8.4.1=1
- ssl_match_hostname=3.4.0.2=py27_0
- tk=8.5.18=0
- tornado=4.2.1=py27_0
- ujson=1.33=py27_0
- websocket-client=0.12.0=py27_1
- werkzeug=0.10.4=py27_0
- yaml=0.1.6=0
- zeromq=4.0.5=0
- zlib=1.2.8=1
- pip:
  - backports.ssl-match-hostname==3.4.0.2
  - beautifulsoup4==4.3.2

